version: '3'

services:

  test.task.app:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '20080:80'

  test.task.db:
    image: mysql:5.7
    ports:
      - 33066:3306
    volumes:
      - test.task.db.volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2base
      - MYSQL_USER=yii2base
      - MYSQL_PASSWORD=secret

volumes:
  test.task.db.volume:
